name: getx_movie
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.16.1 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  dio: ^4.0.4
  get: 4.6.1
  flutter: 
    sdk: flutter
  heroicons: ^0.4.0
  google_fonts: ^2.3.1
  shimmer: ^2.0.0
  card_swiper: ^2.0.1

dev_dependencies: 
  flutter_lints: ^1.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

